fix backup on ubuntu

diff --git a/.github/workflows/backup.yml b/.github/workflows/backup.yml
--- a/.github/workflows/backup.yml
+++ b/.github/workflows/backup.yml
@@ -1,39 +1,38 @@
-name: Backup on Push
+# name: Backup on Push
+# on:
+#   push:
+#     branches:
+#       - main
 
-on:
-  push:
-    branches:
-      - main
+# jobs:
+#   deploy:
+#     runs-on: ubuntu-latest
 
-jobs:
-  deploy:
-    runs-on: ubuntu-latest
+#     steps:
+#     - name: Checkout code
+#       uses: actions/checkout@v4
 
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
-
-    - name: Test Internet Connectivity
-      run: |
-        curl https://www.google.com
+#     - name: Test Internet Connectivity
+#       run: |
+#         curl https://www.google.com
     
-    - name: Test Network Connectivity
-      run: |
-        nc -vz 192.168.1.195 22 || echo "Cannot connect to SSH port"
-        ping -c 4 192.168.1.195 || echo "Cannot ping server"
+#     - name: Test Network Connectivity
+#       run: |
+#         nc -vz 192.168.1.195 22 || echo "Cannot connect to SSH port"
+#         ping -c 4 192.168.1.195 || echo "Cannot ping server"
 
-    - name: Debug SSH Configuration
-      run: |
-          cat ~/.ssh/config || echo "No SSH config file"
-          ssh -vvv 192.168.1.195 echo "SSH connection test" 
+#     - name: Debug SSH Configuration
+#       run: |
+#           cat ~/.ssh/config || echo "No SSH config file"
+#           ssh -vvv 192.168.1.195 echo "SSH connection test" 
     
-    - name: Set up SSH key
-      run: |
-        mkdir -p ~/.ssh
-        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
-        chmod 600 ~/.ssh/id_ed25519
-        echo "Host 192.168.1.195\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" > ~/.ssh/config
-        ssh-keyscan -H 192.168.1.195 >> ~/.ssh/known_hosts
+#     - name: Set up SSH key
+#       run: |
+#         mkdir -p ~/.ssh
+#         echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
+#         chmod 600 ~/.ssh/id_ed25519
+#         echo "Host 192.168.1.195\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" > ~/.ssh/config
+#         ssh-keyscan -H 192.168.1.195 >> ~/.ssh/known_hosts
 
-    - name: Sync files
-      run: rsync -avz --exclude '.git' ./ tiozzo@192.168.1.195:/home/tiozzo/Portfolio/
+#     - name: Sync files
+#       run: rsync -avz --exclude '.git' ./ tiozzo@192.168.1.195:/home/tiozzo/Portfolio/
